### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/apinf-bot#17]
@kyyberi I suggest using this project for hosting the Roadmap.
Also the feature requests should be moved from https://github.com/apinf/apinf-bot/issues to https://github.com/apinf/apibot.ai

**Comment by kyyberi** [comment]
+1

**Comment by mauriciovieira** [comment]
@kyyberi As we discussed via chat, my call is to use this project to host Roadmap, planning, marketing campaings, and so on.

**Comment by kyyberi** [comment]
+1

**Comment by mauriciovieira** [comment]
![screen shot 2017-07-10 at 22 57 04](https://user-images.githubusercontent.com/95258/28047818-33d390e2-65c3-11e7-988d-669811f792a3.png)
