### ISSUE TITLE
Push alerts related to my APIs to chat

### ISSUE THREAD

**Issue by kyyberi** [apinf/apinf-bot#4]
As a API Owner I want alerts related to my APIs to be pushed to private channel in Slack. It might be needed that each API has own channel for alerts.

**Comment by kyyberi** [comment]
Alert might be: 

- API is down (which API and when noticed, how many users infected)
- new feedback is added (provide the feedback text to Slack + link to API profile)

**Comment by mauriciovieira** [comment]
Closing in favor of https://github.com/apinf/apibot.ai/issues/33
